name: Steam Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Steam branch to release'
        type: string
        default: ''
      notify:
        description: 'Notify on discord'
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  generate-password:
    runs-on: ubuntu-latest
    outputs:
      password: ${{ steps.random-password.outputs.password }}
    steps:
      - uses: actions/checkout@v4
      - uses: kuma-gee/action-godot/password@main
        id: random-password
        with:
          length: 24

  release-steam:
    runs-on: ubuntu-latest
    needs: [generate-password]
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}
    strategy:
      matrix:
        channel: [windows, linux]
    steps:
      - uses: actions/checkout@v4

      - name: Unpack protected assets
        uses: kuma-gee/action-protect-assets@v1
        with:
          path: ${{ vars.PROJECT_PATH }}/assets
          password: ${{ secrets.ASSETS_PASSWORD }}

      - name: Create Godot Environment File
        uses: kuma-gee/action-godot/godot-env@main
        with:
          output: ${{ vars.PROJECT_PATH }}/build.gd
          code: ${{ secrets.GAME_CODE }}
          version: ${{ github.ref }}
          steam-app: ${{ vars.STEAM_APP }}

      - name: Setup Templates
        uses: kuma-gee/action-godot/setup-template@main
        with:
          version: ${{ vars.GODOT_VERSION }}
          channel: ${{ matrix.channel }}
          encryption-key: ${{ secrets.ENCRYPTION_KEY }}
          game-folder: ${{ vars.PROJECT_PATH }}

      - uses: kuma-gee/action-godot/godot-build@main
        with:
          channel: ${{ matrix.channel }}
          output: build
          game-folder: ${{ vars.PROJECT_PATH }}
          password: ${{ needs.generate-password.outputs.password }}

      # TODO: test
      - uses: game-ci/steam-deploy@v3
        if: github.event.inputs.branch != ''
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}          
          appId: ${{ vars.STEAM_APP }}
          buildDescription: $GITHUB_REF_NAME
          rootPath: build
          depot1Path: StandaloneWindows64
          depot1InstallScriptPath: StandaloneWindows64/install_script.vdf
          depot2Path: StandaloneLinux64
          releaseBranch: ${{ github.event.inputs.branch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.channel }}
          path: build/*

  release-steam-github:
    needs: [release-steam, generate-password]
    uses: kuma-gee/action-godot/.github/workflows/github-release.yml@main
    with:
      artifact: release-*
      name: ${{ vars.GAME_NAME }}
      branch: ${{ inputs.branch }}
      notify: ${{ inputs.notify }}
    secrets:
      discord-webhook: ${{ secrets.DISCORD_RELEASE_HOOK }}
      password: ${{ needs.generate-password.outputs.password }}